### ISSUE TITLE
No 1.20 support

### ISSUE THREAD

**Issue by JulianTechDL1** [e-im/RandomControl#2]
Hey,
I found no other way to contact you thats why im making this Issue Report.
We need your Plugin for our Anarchie server which is running on Paper 1.20.1.
Is there any way you could update you plugin?
That qould be super helpful!

Greetings Julian

**Comment by e-im** [comment]
Have you tried it on 1.20? If it didn't work, what happened–– was anything logged?

I hadn't really intended to work on this any more before addressing #1, which is potentially never as I've lost interest and never used this personally.

**Comment by JulianTechDL1** [comment]
I tried it out on 1.20 and it works. sorry for making this useless request. Maybe update the supportet version list on Modrith.
Thank you.
